code-insiders --install-extension alefragnani.project-manager
code-insiders --install-extension ban.spellright
code-insiders --install-extension christian-kohler.npm-intellisense
code-insiders --install-extension christian-kohler.path-intellisense
code-insiders --install-extension CoenraadS.bracket-pair-colorizer-2
code-insiders --install-extension dbaeumer.vscode-eslint
code-insiders --install-extension docsmsft.docs-article-templates
code-insiders --install-extension docsmsft.docs-markdown
code-insiders --install-extension docsmsft.docs-preview
code-insiders --install-extension docsmsft.docs-yaml
code-insiders --install-extension dsznajder.es7-react-js-snippets
code-insiders --install-extension eamodio.gitlens
code-insiders --install-extension eg2.vscode-npm-script
code-insiders --install-extension esbenp.prettier-vscode
code-insiders --install-extension GitHub.vscode-pull-request-github
code-insiders --install-extension jkjustjoshing.vscode-text-pastry
code-insiders --install-extension johnpapa.vscode-peacock
code-insiders --install-extension jpoissonnier.vscode-styled-components
code-insiders --install-extension kumar-harsh.graphql-for-vscode
code-insiders --install-extension liximomo.sftp
code-insiders --install-extension lXSPandora.vscode-styled-components-snippets
code-insiders --install-extension mechatroner.rainbow-csv
code-insiders --install-extension mrmlnc.vscode-scss
code-insiders --install-extension ms-azuretools.vscode-docker
code-insiders --install-extension MS-CEINTL.vscode-language-pack-en-GB
code-insiders --install-extension ms-python.python
code-insiders --install-extension ms-vscode.github-issues-prs
code-insiders --install-extension ms-vscode.vscode-typescript-tslint-plugin
code-insiders --install-extension ms-vscode.wordcount
code-insiders --install-extension ms-vsliveshare.vsliveshare
code-insiders --install-extension ms-vsliveshare.vsliveshare-audio
code-insiders --install-extension ms-vsliveshare.vsliveshare-pack
code-insiders --install-extension Orta.vscode-jest
code-insiders --install-extension pflannery.vscode-versionlens
code-insiders --install-extension pnp.polacode
code-insiders --install-extension Prisma.prisma
code-insiders --install-extension Prisma.vscode-graphql
code-insiders --install-extension rebornix.ruby
code-insiders --install-extension redhat.vscode-yaml
code-insiders --install-extension scala-lang.scala
code-insiders --install-extension scalameta.metals
code-insiders --install-extension shinnn.stylelint
code-insiders --install-extension streetsidesoftware.code-spell-checker
code-insiders --install-extension VisualStudioExptTeam.vscodeintellicode
code-insiders --install-extension wix.vscode-import-cost
