code --install-extension alefragnani.project-manager
code --install-extension ban.spellright
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension docsmsft.docs-article-templates
code --install-extension docsmsft.docs-markdown
code --install-extension docsmsft.docs-preview
code --install-extension docsmsft.docs-yaml
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.vscode-pull-request-github
code --install-extension jkjustjoshing.vscode-text-pastry
code --install-extension johnpapa.vscode-peacock
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension liximomo.sftp
code --install-extension lXSPandora.vscode-styled-components-snippets
code --install-extension mechatroner.rainbow-csv
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-en-GB
code --install-extension ms-python.python
code --install-extension ms-vscode.github-issues-prs
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vscode.wordcount
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension Orta.vscode-jest
code --install-extension pflannery.vscode-versionlens
code --install-extension pnp.polacode
code --install-extension Prisma.prisma
code --install-extension Prisma.vscode-graphql
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-yaml
code --install-extension scala-lang.scala
code --install-extension scalameta.metals
code --install-extension shinnn.stylelint
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wix.vscode-import-cost
