code --install-extension aaronthomas.vscode-snazzy-operator
code --install-extension alefragnani.project-manager
code --install-extension asvetliakov.snapshot-tools
code --install-extension auiworks.amvim
code --install-extension ban.spellright
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension castwide.solargraph
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cmstead.jsrefactor
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension geddski.macros
code --install-extension GitHub.vscode-pull-request-github
code --install-extension jkjustjoshing.vscode-text-pastry
code --install-extension johnathanludwig.fileswitcher
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension karunamurti.rspec-snippets
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension liximomo.sftp
code --install-extension lXSPandora.vscode-styled-components-snippets
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension misogi.ruby-rubocop
code --install-extension mjmcloug.vscode-elixir
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-python.python
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension Orta.vscode-jest
code --install-extension PeterJausovec.vscode-docker
code --install-extension pflannery.vscode-versionlens
code --install-extension Pivotal.vscode-manifest-yaml
code --install-extension pnp.polacode
code --install-extension pranaygp.vscode-css-peek
code --install-extension Prisma.vscode-graphql
code --install-extension rebornix.ruby
code --install-extension rust-lang.rust
code --install-extension sdras.night-owl
code --install-extension shinnn.stylelint
code --install-extension sleistner.vscode-fileutils
code --install-extension stkb.rewrap
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension sysoev.language-stylus
code --install-extension techer.open-in-browser
code --install-extension toasty-technologies.octave
code --install-extension vscodevim.vim
code --install-extension WallabyJs.quokka-vscode
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
